# Generated by Django 4.2.9 on 2024-01-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_acad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
